inputs:
  where:
    description: the "root" for the blog-like pages
    required: true

runs:
  using: composite
  steps:
    - run: |
        import os

        ## inputs
        ipts = {
          'where': os.environ['IPT__where'],
          'ver': os.environ['ENV__ACTION_REF'],  # the Action version.
        }

        print('─'*99)
        for k,v in os.environ.items():
          print(f"{repr(k)}: {repr(v)}")
      shell: python
      env:
        IPT__where: ${{ inputs.where }}
        ENV__ACTION_REF: ${{ action.ref }}
